# Generated by Django 3.0.5 on 2020-04-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=128, verbose_name='название задания')),
                ('task_description', models.TextField(verbose_name='описание задания')),
                ('task_date', models.DateTimeField(blank=True, null=True, verbose_name='дата и время задачи')),
                ('task_is_done', models.BooleanField(verbose_name='статус выполнения')),
            ],
        ),
    ]
